steps:
  # Build the Docker image with the build arg
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=https://capstone-backend-657482441130.northamerica-northeast2.run.app/api'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
      - '.'
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdks/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'my-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
      - '--region'
      - 'northamerica-northeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'