<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="IronPython">
      <HintPath>..\..\lib\IronPython.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.Modules">
      <HintPath>..\..\lib\IronPython.Modules.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Scripting">
      <HintPath>..\..\lib\Microsoft.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Dynamic">
      <HintPath>..\..\lib\Microsoft.Dynamic.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
