-- USERS TABLE
CREATE TABLE Users (
    UserID SERIAL PRIMARY KEY,
    Email VARCHAR(255) NOT NULL DEFAULT '',
    Password VARCHAR(255) NOT NULL DEFAULT '',
    IsAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    DisplayName VARCHAR(100) NOT NULL DEFAULT '',
    Bio TEXT,
);

-- PASSWORD RESET TABLE
CREATE TABLE PasswordReset (
    UserID INT PRIMARY KEY REFERENCES Users(UserID) ON DELETE CASCADE,
    ResetCode VARCHAR(100) NOT NULL DEFAULT '',
    TimeCreated TIMESTAMP NOT NULL DEFAULT NOW()
);

-- POSTS TABLE
CREATE TABLE Posts (
    PostID SERIAL PRIMARY KEY,
    UserID INT NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    Title VARCHAR(255) NOT NULL DEFAULT '',
    Description TEXT,
    NumberOfLikes INT NOT NULL DEFAULT 0,
    FileLocation VARCHAR(255) NOT NULL DEFAULT '',
    Created TIMESTAMP NOT NULL DEFAULT NOW(),
    LastEdited TIMESTAMP
);

-- FAVOURITES TABLE (JOIN BETWEEN USERS AND POSTS)
CREATE TABLE Favourites (
    UserID INT NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    PostID INT NOT NULL REFERENCES Posts(PostID) ON DELETE CASCADE,
    PRIMARY KEY (UserID, PostID)
);

-- TAGS TABLE (JOIN BETWEEN POSTS AND TAGS)
CREATE TABLE Tags (
    PostID INT NOT NULL REFERENCES Posts(PostID) ON DELETE CASCADE,
    TagName VARCHAR(100) NOT NULL DEFAULT '',
    PRIMARY KEY (PostID, TagName)
);
